name: Build Web App
 
on: [push]
 
jobs:
  build:
 
    runs-on: self-hosted
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
     
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1      
   
     
    - name: Setup NuGet.exe for use with actions 
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget
      run: nuget restore WebApplication1.sln
     
    - name: Build Solution
      run: msbuild WebApplication1.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishUrl="bin\Release\Publish"
     
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: H:\deploy\
     
